---
name: Docker Image CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
        
    - name: Build and push image amd64
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./amd64/Dockerfile
        platforms: linux/amd64
        tags: engineers4cloud/docker:latest
        push: true
        
    - name: Build and push image arm64
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./arm64/Dockerfile
        platforms: linux/arm64
        tags: engineers4cloud/docker:latest
        push: true    
    
